### ISSUE TITLE
File name strings, response to comments from our CSV testing

### ISSUE THREAD

**Issue by SummerLeaves** [umd-lhcb/COMET-cmd-gen#3]
Hi,

Clarification on the string issue in my CSV file generator, following the comments given after my remark on the "ugliness" and necessity of having quotation marks within the string command.

The string quotation marks are required, as I have the CSV file generator now.

As shown in these snapshots, it's a run-error without them. Python will refuse to read it, and the CSV file generator will not work. 

Otherwise, str() recognizes the input as a variable or object. That's needed for iterating the nTx file number, but unnecessary for anything else. 

IDE warnings:
![why strings are the way they are](https://user-images.githubusercontent.com/33738176/52836267-0fe08980-30b8-11e9-98cd-f1f0fbf9d4d2.PNG)

Run file error message:
![error in str](https://user-images.githubusercontent.com/33738176/52836256-0525f480-30b8-11e9-9ad7-ce0d26382b0f.PNG)

As it is now, a working CSV file generator without warnings:
![fixed](https://user-images.githubusercontent.com/33738176/52836275-1a9b1e80-30b8-11e9-9c93-e81e33e88888.PNG)

This is for reference as I move to improve and expand on the generator's functionality.

@manuelfs @wcparker @yipengsun

**Comment by yipengsun** [comment]
To concatenate strings in Python, I'd propose the following way:
```python
'str1' + 'str2' + 'str3'
```

I would say that `str` fails in your case because probably you didn't define a variable with name `.csv` (not sure if it's legal in Python, but this is a different matter).

BTW: I think you can attach pictures directly to the issue report, and there's no need to upload these images to the actual repository.

I have uploaded your images to the issue directly, and noticed that the first and the third images are identical, please also fix this.

**Comment by yipengsun** [comment]
@SummerLeaves have you tried my snippets? If that works, let's use my snippets and close this issue.

**Comment by SummerLeaves** [comment]
Hi Yipeng, @yipengsun 

Sorry for the late reply! Took your snippet and replaced the file-name loop with it, tested it and compared it with the reference files. Appreciate the help.

**Comment by yipengsun** [comment]
Another thing: Inside the for loop, currrent:
```python
for y in range(0, 20):
    ...
    y = y+1
```

The `y = y+1` line is not needed.
