### ISSUE TITLE
Suggestions on filenames

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/COMET-cmd-gen#4]
I'd like to suggesting all lower case filenames, and **replace** white space with a underscore `_`. The main reason is that filenames are (supposedly) easier to type in linux if they don't contain whitespaces:
![typing_filename_with_space_in_linux](https://user-images.githubusercontent.com/33738176/52836978-e07f4c00-30ba-11e9-905b-1ec9fddce868.png)

**Comment by SummerLeaves** [comment]
Thanks for the heads-up; removed white spaces and lower-cased the relevant files. I left capital letters in appropriate places for the generator and reference files because it's easier to read that way, but please let me know if I should replace those as well.

@yipengsun Gonna be adding "junk data" modularity later today or tomorrow.
